### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by yolinfeng** [jootnet/mir2.core#1]
写了这么多，你给写个demo吧，我都不知道这个要怎么用，没有文档，起码给个demo看看也好啊。。。

**Comment by ooocici** [comment]
传奇资源文件在wil,wis,wzl类中,通过构造函数使用.
传奇地图文件再maps类中使用

**Comment by shebin1234** [comment]
亲，人物，地图，怪物这些都试了下，没问题，但是魔法图片看起来有黑色背景。这个要怎么去除呢。按照文章中介绍的，传奇2中没有纯黑色，通过判断R,G,B是否同时为0，添加透明效果的方法似乎无效。

**Comment by jootnet** [comment]
很久没做这方面工作了，后续有时间会更新详细的demo。可以看看另外一个项目m2client-java中的代码，我是以盛大热血传奇10周年客户端为资源供应的，新版的客户端可能会有问题

**Comment by jjuu** [comment]
期待demo

**Comment by KevinSu1991** [comment]
> 很久没做这方面工作了，后续有时间会更新详细的demo。可以看看另外一个项目m2client-java中的代码，我是以盛大热血传奇10周年客户端为资源供应的，新版的客户端可能会有问题



> 亲，人物，地图，怪物这些都试了下，没问题，但是魔法图片看起来有黑色背景。这个要怎么去除呢。按照文章中介绍的，传奇2中没有纯黑色，通过判断R,G,B是否同时为0，添加透明效果的方法似乎无效。

大佬，请问下 ImageInfo对象我都解析出来了，Texture也可以获取到。怎么保存为图片文件？

**Comment by KevinSu1991** [comment]
搞定了，大佬的m2client-java 这个工程里的Texture类里有toBufferedImage()方法。

**Comment by KevinSu1991** [comment]
> 代码

大佬，请问下导出来的bmp图片有黑色背景怎么处理？

**Comment by KevinSu1991** [comment]
> > 代码
> 
> 大佬，请问下导出来的bmp图片有黑色背景怎么处理？

感谢 已搞定

**Comment by jootnet** [comment]
请参见当前账号的另一个项目JootM2Client。我会不定期更新功能
