### ISSUE TITLE
新地图导出问题

### ISSUE THREAD

**Issue by killbad** [jootnet/mir2.core#2]
新地图的map文件解析里， VerFlag既不为0，也为1，单个地图块的 bytesize 远远大于12，很多等于36，直接跳过只是程序不报错，生成出来的文件完全不能用，请问有这方面的资料和介绍吗？

**Comment by jootnet** [comment]
我最多测试到2.0.5.90。我一般使用的客户端版本是10周年，也没什么特别意义，就是当初拿到的第一个安装包。至于兼容新的版本，在我这里优先级较低

**Comment by jootnet** [comment]
> 

我下载了官方最新的客户端2.0.10.5。经测试，比奇（地图名0.map）是12字节，盟重（地图名3.map）是14。请问=36的地图名称是？
